# Change these first
owner: quesst-technologies # Your GitHub organization or username, where this repository lives
repo: qst-client-status-all # The name of this repository

sites:
  - name: Gateway Service
    url: https://quessttechnologies.com/gateway/healthcheck

  - name: Analytics Service
    url: https://quessttechnologies.com/analytics/healthcheck

  - name: Api Service
    url: https://quessttechnologies.com/api/healthcheck

  - name: Cron Service
    url: https://quessttechnologies.com/cron/healthcheck
    
  - name: Email Service
    url: https://quessttechnologies.com/email/healthcheck

  - name: Frontend Service
    url: https://quessttechnologies.com/frontend/healthcheck

  - name: Notifications Service
    url: https://quessttechnologies.com/notifications/healthcheck
    
  - name: Search Service
    url: https://quessttechnologies.com/search/healthcheck
    
  - name: Socket Service
    url: https://quessttechnologies.com/socket/healthcheck

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.admin.quessttechnologies.com
#   baseUrl: /qst-client-status-all
  logoUrl: https://s3.ap-south-1.amazonaws.com/content.quessttechnologies.com/configuration/assets/logo/png/Quesst(Beta)_En_Blue_Horizonal.png
  name: ""
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub!!!"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
